trigger:
  branches:
    include:
      - main

stages:

  - stage: Build
    displayName: "Build"
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Branche : $(Build.SourceBranchName)"
              echo "Build ID : $(Build.BuildId)"
            displayName: 'Infos du build'

          - script: pip install -r requirements.txt
            displayName: 'Installation des dépendances'

          - script: |
              docker build -t althea-app:$(Build.BuildId) .
              echo "Image Docker construite avec succès"
            displayName: 'Build image Docker'

  - stage: Test
    displayName: "Tests"
    dependsOn: Build
    jobs:
      - job: TestJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: pip install -r requirements.txt
            displayName: 'Installation'

          - script: pytest test_app.py -v
            displayName: 'Tests unitaires avec pytest'

  - stage: Deploy
    displayName: "Deploiement"
    dependsOn: Test
    jobs:
      - job: DeployJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: |
              echo "Deploiement effectue avec succes"
              echo "Version : $(Build.BuildId)"
            displayName: 'Deploy'
